import requests
import json

BASE_URL = "http://localhost:5000/api/analyze/text"

# Test inputs A through H
TEST_CASES = [
    ("A. Single Word", "Hello"),
    ("B. Two Words", "Hello world"),
    ("C. 4-6 Words Borderline", "Generated by artificial intelligence model"),
    ("C2. 4-6 Words Decisive Human", "This is my daily coffee"),
    ("D. Normal Sentence", "I forgot my laptop charger at home and need someone to send me the lecture notes from today."),
    ("E. Medium Paragraph", "In summary, the rapid evolution of artificial intelligence represents a profound paradigm shift across modern technological frameworks, necessitating robust algorithmic architectures and multi-layered verification protocols."),
    ("F. 500-word document", ("Artificial intelligence leverages multifaceted machine learning algorithms to systematically optimize computational workflows. " * 35)),
    ("G. 1000-word document", ("Artificial intelligence leverages multifaceted machine learning algorithms to systematically optimize computational workflows. " * 70)),
    ("H. Mixed Long Document", ("I woke up yesterday around seven in the morning and drove to the office for a team meeting with Sarah. " * 15) + "\n\n" + ("Artificial intelligence leverages multifaceted machine learning algorithms to systematically optimize computational workflows. " * 15))
]

def simulate_frontend_rendering(data):
    result = data.get("result", "UNKNOWN")
    word_count = data.get("word_count", "--")
    length_group = data.get("length_group", "unknown")
    ai_prob = data.get("ai_probability")
    human_prob = data.get("human_probability")
    confidence = data.get("confidence")
    reason = data.get("reason", "")
    
    ui_output = {}
    
    if result == "INSUFFICIENT_EVIDENCE":
        ui_output["badge"] = "INSUFFICIENT EVIDENCE"
        ui_output["badge_class"] = "badge insufficient"
        ui_output["confidence_text"] = "N/A"
        ui_output["alert_visible"] = True
        ui_output["alert_title"] = "Insufficient Evidence"
        ui_output["alert_reason"] = reason or "Too little text is available for reliable AI-vs-human classification."
        ui_output["prob_bars_visible"] = False
        ui_output["method"] = "Context Verification"
    elif result == "UNCERTAIN":
        ui_output["badge"] = "UNCERTAIN / BORDERLINE"
        ui_output["badge_class"] = "badge uncertain"
        ui_output["confidence_text"] = "Inconclusive"
        ui_output["alert_visible"] = True
        ui_output["alert_title"] = "Uncertain / Borderline Prediction"
        ui_output["alert_reason"] = reason or "The available text provides limited evidence, so the prediction is not confident."
        ui_output["prob_bars_visible"] = True if ai_prob is not None else False
        ui_output["ai_prob_text"] = f"{ai_prob}%" if ai_prob is not None else "N/A"
        ui_output["human_prob_text"] = f"{human_prob}%" if human_prob is not None else "N/A"
        ui_output["method"] = "ML Inference (Borderline Range)"
    elif result == "AI-GENERATED":
        ui_output["badge"] = "AI-GENERATED"
        ui_output["badge_class"] = "badge ai"
        ui_output["confidence_text"] = f"{confidence}%" if confidence is not None else (f"{ai_prob}%" if ai_prob is not None else "--")
        ui_output["alert_visible"] = True if data.get("is_short_text") else False
        ui_output["alert_title"] = "Short Text Notice"
        ui_output["alert_reason"] = reason
        ui_output["prob_bars_visible"] = True
        ui_output["ai_prob_text"] = f"{ai_prob}%" if ai_prob is not None else "--"
        ui_output["human_prob_text"] = f"{human_prob}%" if human_prob is not None else "--"
        ui_output["method"] = "V2 Improved ML Model"
    else: # HUMAN-WRITTEN
        ui_output["badge"] = "HUMAN-WRITTEN"
        ui_output["badge_class"] = "badge human"
        ui_output["confidence_text"] = f"{confidence}%" if confidence is not None else (f"{human_prob}%" if human_prob is not None else "--")
        ui_output["alert_visible"] = True if data.get("is_short_text") else False
        ui_output["alert_title"] = "Short Text Notice"
        ui_output["alert_reason"] = reason
        ui_output["prob_bars_visible"] = True
        ui_output["ai_prob_text"] = f"{ai_prob}%" if ai_prob is not None else "--"
        ui_output["human_prob_text"] = f"{human_prob}%" if human_prob is not None else "--"
        ui_output["method"] = "V2 Improved ML Model"

    ui_output["chunk_analysis_displayed"] = False
    return ui_output

def main():
    print("="*80)
    print("PHASE 2 FRONTEND INTEGRATION TEST SUITE (TEST CASES A - H)")
    print("="*80)
    
    for name, text in TEST_CASES:
        print(f"\n--- {name} (Words: {len(text.split())}) ---")
        resp = requests.post(BASE_URL, json={"text": text}, timeout=30)
        if resp.status_code != 200:
            print(f"ERROR: HTTP {resp.status_code}")
            continue
        data = resp.json()
        ui = simulate_frontend_rendering(data)
        
        print(f"  Backend Result       : {data.get('result')}")
        print(f"  UI Badge Display     : [{ui['badge']}] (CSS: {ui['badge_class']})")
        print(f"  UI Confidence Display: {ui['confidence_text']}")
        if ui['prob_bars_visible']:
            print(f"  UI Probabilities     : AI = {ui['ai_prob_text']} | Human = {ui['human_prob_text']}")
        else:
            print(f"  UI Probabilities     : Hidden (Neutral / Insufficient Context)")
        if ui['alert_visible']:
            print(f"  UI Notice Banner     : [{ui['alert_title']}] \"{ui['alert_reason']}\"")
        print(f"  Chunk Analysis Shown : {ui['chunk_analysis_displayed']} (Clean whole-document UI)")

if __name__ == "__main__":
    main()
