import urllib.request
import json

def test_text(label, text):
    req = urllib.request.Request(
        'http://localhost:5000/api/analyze/text',
        data=json.dumps({'text': text}).encode('utf-8'),
        headers={'Content-Type': 'application/json'}
    )
    with urllib.request.urlopen(req) as resp:
        res = json.loads(resp.read().decode())
        print(f"\n========================================")
        print(f"TEST: {label}")
        print(f"INPUT: \"{text[:80].strip()}...\" (Word count: {len(text.split())})")
        print(f"RESULT: {res.get('result')} (Confidence: {res.get('confidence')})")
        print(f"AI Prob: {res.get('ai_probability')}% | Human Prob: {res.get('human_probability')}%")
        print(f"Short Text: {res.get('is_short_text')} | Limited Context: {res.get('limited_context')}")
        if res.get('reason'):
            print(f"Reason: {res.get('reason')}")
        if res.get('number_of_chunks'):
            print(f"Chunks ({res.get('number_of_chunks')}): Global AI={res.get('global_ai_probability')}% | Mean Chunk AI={res.get('mean_chunk_ai_probability')}% | Peak Chunk AI={res.get('peak_chunk_ai_probability')}% | AI Ratio={res.get('ai_chunk_ratio')}%")
            for chunk in res.get('chunks', []):
                print(f"  - Chunk {chunk['chunk_index']} ({chunk['word_count']} words): AI={chunk['ai_probability']}% -> {chunk['result']}")

if __name__ == '__main__':
    # 1. 1 Word
    test_text('1. Single Word (1 word)', 'Hello')

    # 2. 2 Words
    test_text('2. Two Words (2 words)', 'Hello world')

    # 3. 4–6 Words AI-like
    test_text('3. AI-like Short Sentence (5 words)', 'Generated by artificial intelligence model')

    # 4. 4–6 Words Human-like
    test_text('4. Human-like Short Sentence (4 words)', 'Thanks for the coffee')

    # 5. Normal 10–20 Words Sentence
    test_text('5. Normal Sentence (16 words)', 'I forgot my laptop charger at home and need someone to send me the lecture notes.')

    # 6. Medium Paragraph
    test_text('6. Medium Paragraph (25 words)', 'In summary, the rapid evolution of artificial intelligence represents a profound paradigm shift across modern technological frameworks, necessitating robust algorithmic architectures and multi-layered verification protocols.')

    # 7. Long Multi-Paragraph Text
    long_doc = """Artificial intelligence has transformed the landscape of computational linguistics and natural language generation. Modern large language models can generate fluent, coherent, and highly sophisticated essays across diverse domains.

However, distinguishing synthetic writing from authentic human discourse has become an essential cybersecurity priority. Detecting automated text requires robust multi-modal feature representations, including n-gram TF-IDF statistics, semantic embeddings, and lexical burstiness patterns.

By combining sliding window sentence segmentation with fused representation classifiers, content forensic systems can identify subtle localized AI insertions across complex multi-page documents."""

    test_text('7. Long Multi-Paragraph Document (78 words, 6 sentences)', long_doc)

    # 8. Mixed Human + AI Document
    mixed_doc = """Yesterday morning I took a short walk around the campus park before heading to the computer science department library to finish my assignment. The weather was unusually pleasant and cool for this time of the year. I met a couple of classmates on the way and we discussed our final semester project presentations.

In summary, the rapid evolution of artificial intelligence represents a profound paradigm shift across modern technological frameworks, necessitating robust algorithmic architectures and multi-layered verification protocols. The synthesis of generative representations introduces novel socio-technical considerations that demand rigorous empirical validation.

After the library session I went to the cafeteria to grab lunch and met my project supervisor to get feedback on our report draft. We agreed to conduct another round of testing on the validation dataset before the final submission."""

    test_text('8. Mixed Human + AI Multi-Paragraph Document (139 words, 7 sentences)', mixed_doc)
